model_name: GCN
dataset: cora
num_layers: 2
num_parts: 40
batch_size: 10
hidden_size: 16
lr: 0.01
weight_decay: 0.0005
dropout: 0.0
gcn_norm: True
grad_norm: True
gen_train_data_in_advance: True
load_feat_to_gpu: True
epochs: 200
